//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mygod.HideEar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.HideEar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 掩耳简介：
        ///　　该软件极其适合批量下载文件，当下载文件数及其多时可以说“迅雷不及掩耳”。（但是不推荐你下载大文件）你也可以用这款软件获取YouTube的下载链接，也可以转换普通、迅雷、快车、旋风、RayFile与Mygod离线下载器链接。
        ///　　如果你觉得下载速度过慢，可以到设置中把任务数调大一些即可。
        ///
        ///使用帮助：
        ///　　将要下载的链接粘贴进来，点击“掩耳下载”即可开始下载，点击“使用默认工具下载”可启动对应的下载工具下载，点击“转换到”将链接转换到指定格式。
        ///
        ///分析YouTube视频下载链接：
        ///　　1.  在中国大陆使用此软件下载YouTube视频必须翻墙。（使用代理？去设置里先设置一下吧）
        ///　　2.  在“掩耳”主界面内粘贴带有视频的网页地址后点击“分析YouTube视频链接”。
        ///　　3.  右击你要下载的格式下载。
        ///
        ///注意：YouTube视频不适合离线下载因为下载需要使用指定的IP，如果你想用离线下载器下载YouTube视频，推荐使用你管下载者 Online：http://mygod.apphb.com/Online/NiGuanDownloader.aspx
        ///
        ///特别感谢：
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
    }
}
